### ISSUE TITLE
Python2 installation issue with numdifftools

### ISSUE THREAD

**Issue by JohannesBuchner** [giacomov/astromodels#65]
Probably not a astromodels issue, but with numdifftools:
```
$ python2 setup.py install --user

 Xspec is detected. Will compile the Xspec extension.

Found library XSFunctions in /home/user/bin/xspec/x86_64-unknown-linux-gnu-libc2.25/lib
Found library XSModel in /home/user/bin/xspec/x86_64-unknown-linux-gnu-libc2.25/lib
Found library XSUtil in /home/user/bin/xspec/x86_64-unknown-linux-gnu-libc2.25/lib
Found library XS in /home/user/bin/xspec/x86_64-unknown-linux-gnu-libc2.25/lib
Found library cfitsio in None
Found library CCfits_2.5 in /home/user/bin/xspec/x86_64-unknown-linux-gnu-libc2.25/lib
Found library wcs in None
Found library gfortran in None
running install
running bdist_egg
running egg_info
writing requirements to astromodels.egg-info/requires.txt
writing astromodels.egg-info/PKG-INFO
writing top-level names to astromodels.egg-info/top_level.txt
writing dependency_links to astromodels.egg-info/dependency_links.txt
package init file 'astromodels/tests/__init__.py' not found (or not a regular file)
reading manifest template 'MANIFEST.in'
writing manifest file 'astromodels.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/astromodels
creating build/bdist.linux-x86_64/egg/astromodels/xspec
creating build/bdist.linux-x86_64/egg/astromodels/xspec/include
creating build/bdist.linux-x86_64/egg/astromodels/xspec/include/sherpa
copying build/lib.linux-x86_64-2.7/astromodels/xspec/include/sherpa/fcmp.hh -> build/bdist.linux-x86_64/egg/astromodels/xspec/include/sherpa
copying build/lib.linux-x86_64-2.7/astromodels/xspec/include/sherpa/extension.hh -> build/bdist.linux-x86_64/egg/astromodels/xspec/include/sherpa
copying build/lib.linux-x86_64-2.7/astromodels/xspec/include/sherpa/constants.hh -> build/bdist.linux-x86_64/egg/astromodels/xspec/include/sherpa
creating build/bdist.linux-x86_64/egg/astromodels/xspec/include/sherpa/astro
copying build/lib.linux-x86_64-2.7/astromodels/xspec/include/sherpa/astro/xspec_extension.hh -> build/bdist.linux-x86_64/egg/astromodels/xspec/include/sherpa/astro
copying build/lib.linux-x86_64-2.7/astromodels/xspec/include/sherpa/array.hh -> build/bdist.linux-x86_64/egg/astromodels/xspec/include/sherpa
copying build/lib.linux-x86_64-2.7/astromodels/xspec/__init__.py -> build/bdist.linux-x86_64/egg/astromodels/xspec
copying build/lib.linux-x86_64-2.7/astromodels/xspec/factory.py -> build/bdist.linux-x86_64/egg/astromodels/xspec
copying build/lib.linux-x86_64-2.7/astromodels/xspec/xspec_settings.py -> build/bdist.linux-x86_64/egg/astromodels/xspec
copying build/lib.linux-x86_64-2.7/astromodels/xspec/_xspec.so -> build/bdist.linux-x86_64/egg/astromodels/xspec
copying build/lib.linux-x86_64-2.7/astromodels/xspec/README -> build/bdist.linux-x86_64/egg/astromodels/xspec
creating build/bdist.linux-x86_64/egg/astromodels/xspec/src
copying build/lib.linux-x86_64-2.7/astromodels/xspec/src/_xspec.cc -> build/bdist.linux-x86_64/egg/astromodels/xspec/src
copying build/lib.linux-x86_64-2.7/astromodels/xspec/LICENSE -> build/bdist.linux-x86_64/egg/astromodels/xspec
creating build/bdist.linux-x86_64/egg/astromodels/sources
copying build/lib.linux-x86_64-2.7/astromodels/sources/point_source.py -> build/bdist.linux-x86_64/egg/astromodels/sources
copying build/lib.linux-x86_64-2.7/astromodels/sources/__init__.py -> build/bdist.linux-x86_64/egg/astromodels/sources
copying build/lib.linux-x86_64-2.7/astromodels/sources/source.py -> build/bdist.linux-x86_64/egg/astromodels/sources
copying build/lib.linux-x86_64-2.7/astromodels/sources/extended_source.py -> build/bdist.linux-x86_64/egg/astromodels/sources
copying build/lib.linux-x86_64-2.7/astromodels/sources/particle_source.py -> build/bdist.linux-x86_64/egg/astromodels/sources
creating build/bdist.linux-x86_64/egg/astromodels/functions
copying build/lib.linux-x86_64-2.7/astromodels/functions/functions_3D.py -> build/bdist.linux-x86_64/egg/astromodels/functions
copying build/lib.linux-x86_64-2.7/astromodels/functions/functions_2D.py -> build/bdist.linux-x86_64/egg/astromodels/functions
copying build/lib.linux-x86_64-2.7/astromodels/functions/function.py -> build/bdist.linux-x86_64/egg/astromodels/functions
creating build/bdist.linux-x86_64/egg/astromodels/functions/dark_matter
copying build/lib.linux-x86_64-2.7/astromodels/functions/dark_matter/__init__.py -> build/bdist.linux-x86_64/egg/astromodels/functions/dark_matter
copying build/lib.linux-x86_64-2.7/astromodels/functions/dark_matter/dm_models.py -> build/bdist.linux-x86_64/egg/astromodels/functions/dark_matter
copying build/lib.linux-x86_64-2.7/astromodels/functions/__init__.py -> build/bdist.linux-x86_64/egg/astromodels/functions
copying build/lib.linux-x86_64-2.7/astromodels/functions/priors.py -> build/bdist.linux-x86_64/egg/astromodels/functions
copying build/lib.linux-x86_64-2.7/astromodels/functions/template_model.py -> build/bdist.linux-x86_64/egg/astromodels/functions
copying build/lib.linux-x86_64-2.7/astromodels/functions/functions.py -> build/bdist.linux-x86_64/egg/astromodels/functions
copying build/lib.linux-x86_64-2.7/astromodels/__init__.py -> build/bdist.linux-x86_64/egg/astromodels
creating build/bdist.linux-x86_64/egg/astromodels/data
creating build/bdist.linux-x86_64/egg/astromodels/data/dark_matter
copying build/lib.linux-x86_64-2.7/astromodels/data/dark_matter/gammamc_dif.dat -> build/bdist.linux-x86_64/egg/astromodels/data/dark_matter
copying build/lib.linux-x86_64-2.7/astromodels/data/dark_matter/dmSpecTab.npy -> build/bdist.linux-x86_64/egg/astromodels/data/dark_matter
creating build/bdist.linux-x86_64/egg/astromodels/data/tests
copying build/lib.linux-x86_64-2.7/astromodels/data/tests/test.yaml -> build/bdist.linux-x86_64/egg/astromodels/data/tests
copying build/lib.linux-x86_64-2.7/astromodels/data/tests/black_hole.yaml -> build/bdist.linux-x86_64/egg/astromodels/data/tests
copying build/lib.linux-x86_64-2.7/astromodels/data/tests/simple_source.yaml -> build/bdist.linux-x86_64/egg/astromodels/data/tests
copying build/lib.linux-x86_64-2.7/astromodels/version.py -> build/bdist.linux-x86_64/egg/astromodels
creating build/bdist.linux-x86_64/egg/astromodels/utils
copying build/lib.linux-x86_64-2.7/astromodels/utils/configuration.py -> build/bdist.linux-x86_64/egg/astromodels/utils
copying build/lib.linux-x86_64-2.7/astromodels/utils/angular_distance.py -> build/bdist.linux-x86_64/egg/astromodels/utils
copying build/lib.linux-x86_64-2.7/astromodels/utils/vincenty.py -> build/bdist.linux-x86_64/egg/astromodels/utils
copying build/lib.linux-x86_64-2.7/astromodels/utils/valid_variable.py -> build/bdist.linux-x86_64/egg/astromodels/utils
copying build/lib.linux-x86_64-2.7/astromodels/utils/data_files.py -> build/bdist.linux-x86_64/egg/astromodels/utils
copying build/lib.linux-x86_64-2.7/astromodels/utils/io.py -> build/bdist.linux-x86_64/egg/astromodels/utils
copying build/lib.linux-x86_64-2.7/astromodels/utils/__init__.py -> build/bdist.linux-x86_64/egg/astromodels/utils
copying build/lib.linux-x86_64-2.7/astromodels/utils/table.py -> build/bdist.linux-x86_64/egg/astromodels/utils
copying build/lib.linux-x86_64-2.7/astromodels/utils/long_path_formatter.py -> build/bdist.linux-x86_64/egg/astromodels/utils
copying build/lib.linux-x86_64-2.7/astromodels/utils/disk_usage.py -> build/bdist.linux-x86_64/egg/astromodels/utils
copying build/lib.linux-x86_64-2.7/astromodels/utils/pretty_list.py -> build/bdist.linux-x86_64/egg/astromodels/utils
creating build/bdist.linux-x86_64/egg/astromodels/core
copying build/lib.linux-x86_64-2.7/astromodels/core/parameter_transformation.py -> build/bdist.linux-x86_64/egg/astromodels/core
copying build/lib.linux-x86_64-2.7/astromodels/core/memoization.py -> build/bdist.linux-x86_64/egg/astromodels/core
copying build/lib.linux-x86_64-2.7/astromodels/core/spectral_component.py -> build/bdist.linux-x86_64/egg/astromodels/core
copying build/lib.linux-x86_64-2.7/astromodels/core/sky_direction.py -> build/bdist.linux-x86_64/egg/astromodels/core
copying build/lib.linux-x86_64-2.7/astromodels/core/my_yaml.py -> build/bdist.linux-x86_64/egg/astromodels/core
copying build/lib.linux-x86_64-2.7/astromodels/core/model_parser.py -> build/bdist.linux-x86_64/egg/astromodels/core
copying build/lib.linux-x86_64-2.7/astromodels/core/node_ctype.so -> build/bdist.linux-x86_64/egg/astromodels/core
copying build/lib.linux-x86_64-2.7/astromodels/core/units.py -> build/bdist.linux-x86_64/egg/astromodels/core
copying build/lib.linux-x86_64-2.7/astromodels/core/tree.py -> build/bdist.linux-x86_64/egg/astromodels/core
copying build/lib.linux-x86_64-2.7/astromodels/core/__init__.py -> build/bdist.linux-x86_64/egg/astromodels/core
copying build/lib.linux-x86_64-2.7/astromodels/core/thread_safe_unit_format.py -> build/bdist.linux-x86_64/egg/astromodels/core
creating build/bdist.linux-x86_64/egg/astromodels/core/node_ctype
copying build/lib.linux-x86_64-2.7/astromodels/core/node_ctype/node_ctype.cxx -> build/bdist.linux-x86_64/egg/astromodels/core/node_ctype
copying build/lib.linux-x86_64-2.7/astromodels/core/serialization.py -> build/bdist.linux-x86_64/egg/astromodels/core
copying build/lib.linux-x86_64-2.7/astromodels/core/polarization.py -> build/bdist.linux-x86_64/egg/astromodels/core
copying build/lib.linux-x86_64-2.7/astromodels/core/parameter.py -> build/bdist.linux-x86_64/egg/astromodels/core
copying build/lib.linux-x86_64-2.7/astromodels/core/model.py -> build/bdist.linux-x86_64/egg/astromodels/core
creating build/bdist.linux-x86_64/egg/astromodels/tests
copying build/lib.linux-x86_64-2.7/astromodels/tests/test_functions.py -> build/bdist.linux-x86_64/egg/astromodels/tests
copying build/lib.linux-x86_64-2.7/astromodels/tests/test_tree.py -> build/bdist.linux-x86_64/egg/astromodels/tests
copying build/lib.linux-x86_64-2.7/astromodels/tests/test_memoizer.py -> build/bdist.linux-x86_64/egg/astromodels/tests
copying build/lib.linux-x86_64-2.7/astromodels/tests/test_load_xspec_models.py -> build/bdist.linux-x86_64/egg/astromodels/tests
copying build/lib.linux-x86_64-2.7/astromodels/tests/test_point_source.py -> build/bdist.linux-x86_64/egg/astromodels/tests
copying build/lib.linux-x86_64-2.7/astromodels/tests/test_parameter.py -> build/bdist.linux-x86_64/egg/astromodels/tests
copying build/lib.linux-x86_64-2.7/astromodels/tests/test_model.py -> build/bdist.linux-x86_64/egg/astromodels/tests
copying build/lib.linux-x86_64-2.7/astromodels/tests/test_template_model.py -> build/bdist.linux-x86_64/egg/astromodels/tests
byte-compiling build/bdist.linux-x86_64/egg/astromodels/xspec/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/xspec/factory.py to factory.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/xspec/xspec_settings.py to xspec_settings.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/sources/point_source.py to point_source.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/sources/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/sources/source.py to source.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/sources/extended_source.py to extended_source.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/sources/particle_source.py to particle_source.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/functions/functions_3D.py to functions_3D.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/functions/functions_2D.py to functions_2D.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/functions/function.py to function.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/functions/dark_matter/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/functions/dark_matter/dm_models.py to dm_models.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/functions/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/functions/priors.py to priors.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/functions/template_model.py to template_model.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/functions/functions.py to functions.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/utils/configuration.py to configuration.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/utils/angular_distance.py to angular_distance.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/utils/vincenty.py to vincenty.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/utils/valid_variable.py to valid_variable.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/utils/data_files.py to data_files.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/utils/io.py to io.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/utils/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/utils/table.py to table.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/utils/long_path_formatter.py to long_path_formatter.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/utils/disk_usage.py to disk_usage.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/utils/pretty_list.py to pretty_list.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/core/parameter_transformation.py to parameter_transformation.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/core/memoization.py to memoization.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/core/spectral_component.py to spectral_component.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/core/sky_direction.py to sky_direction.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/core/my_yaml.py to my_yaml.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/core/model_parser.py to model_parser.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/core/units.py to units.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/core/tree.py to tree.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/core/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/core/thread_safe_unit_format.py to thread_safe_unit_format.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/core/serialization.py to serialization.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/core/polarization.py to polarization.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/core/parameter.py to parameter.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/core/model.py to model.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/tests/test_functions.py to test_functions.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/tests/test_tree.py to test_tree.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/tests/test_memoizer.py to test_memoizer.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/tests/test_load_xspec_models.py to test_load_xspec_models.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/tests/test_point_source.py to test_point_source.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/tests/test_parameter.py to test_parameter.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/tests/test_model.py to test_model.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/tests/test_template_model.py to test_template_model.pyc
creating stub loader for astromodels/xspec/_xspec.so
creating stub loader for astromodels/core/node_ctype.so
byte-compiling build/bdist.linux-x86_64/egg/astromodels/xspec/_xspec.py to _xspec.pyc
byte-compiling build/bdist.linux-x86_64/egg/astromodels/core/node_ctype.py to node_ctype.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/astromodels/data/functions
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying astromodels.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying astromodels.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying astromodels.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying astromodels.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying astromodels.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist/astromodels-0.5.1-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing astromodels-0.5.1-py2.7-linux-x86_64.egg
Removing /mnt/data/daten/Master/home/.local/lib64/python2.7/site-packages/astromodels-0.5.1-py2.7-linux-x86_64.egg
Copying astromodels-0.5.1-py2.7-linux-x86_64.egg to /mnt/data/daten/Master/home/.local/lib64/python2.7/site-packages
astromodels 0.5.1 is already the active version in easy-install.pth

Installed /mnt/data/daten/Master/home/.local/lib64/python2.7/site-packages/astromodels-0.5.1-py2.7-linux-x86_64.egg
Processing dependencies for astromodels==0.5.1
Searching for numdifftools
Reading https://pypi.python.org/simple/numdifftools/
Downloading https://pypi.python.org/packages/70/25/1af07d513fc5fb60b80c4577971fdd3480f931291f783dde33de178b185f/numdifftools-0.9.20.tar.gz#md5=c0545b8d1d1b4cdd1d5dacd99ff42666
Best match: numdifftools 0.9.20
Processing numdifftools-0.9.20.tar.gz
Writing /tmp/easy_install-nJBrWo/numdifftools-0.9.20/setup.cfg
Running numdifftools-0.9.20/setup.py -q bdist_egg --dist-dir /tmp/easy_install-nJBrWo/numdifftools-0.9.20/egg-dist-tmp-X1wN3R
zip_safe flag not set; analyzing archive contents...

Installed /tmp/easy_install-nJBrWo/numdifftools-0.9.20/.eggs/pyscaffold-2.4.4-py2.7.egg
/usr/lib64/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin answer-testing = yt.utilities.answer_testing.framework:AnswerTesting: super() argument 1 must be type, not None
  RuntimeWarning)
/usr/lib64/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin tap = tap.plugin:TAP: (Pygments 2.2.0 (/usr/lib64/python2.7/site-packages), Requirement.parse('Pygments==2.0.1'))
  RuntimeWarning)
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/lib64/python2.7/site-packages/pbr/util.py", line 267, in cfg_to_args
    wrap_commands(kwargs)
  File "/usr/lib64/python2.7/site-packages/pbr/util.py", line 569, in wrap_commands
    cmdclass = ep.resolve()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2428, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python2.7/site-packages/sphinx/setup_command.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/usr/lib64/python2.7/site-packages/sphinx/application.py", line 33, in <module>
    from sphinx.environment import BuildEnvironment
  File "/usr/lib64/python2.7/site-packages/sphinx/environment/__init__.py", line 45, in <module>
    from sphinx.util.websupport import is_commentable
  File "/usr/lib64/python2.7/site-packages/sphinx/util/websupport.py", line 11, in <module>
    from sphinxcontrib.websupport.utils import is_commentable  # NOQA
  File "/usr/lib64/python2.7/site-packages/sphinxcontrib/websupport/__init__.py", line 15, in <module>
    from sphinxcontrib.websupport.core import WebSupport  # NOQA
  File "/usr/lib64/python2.7/site-packages/sphinxcontrib/websupport/core.py", line 17, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/usr/lib64/python2.7/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/lib64/python2.7/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/lib64/python2.7/site-packages/jinja2/utils.py", line 486, in <module>
    MutableMapping.register(LRUCache)
  File "/usr/lib/python-exec/python2.7/../../../lib64/python2.7/abc.py", line 109, in register
    if issubclass(subclass, cls):
  File "/usr/lib/python-exec/python2.7/../../../lib64/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/usr/lib64/python2.7/site-packages/typing.py", line 1265, in __subclasscheck__
    return super(GenericMeta, self).__subclasscheck__(cls)
TypeError: super() argument 1 must be type, not None
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-nJBrWo/numdifftools-0.9.20/setup.cfg: TypeError: super() argument 1 must be type, not None
```
This was run on 33a71e1a6318e4191975e7ac228f0f9ac2d26524

**Comment by JohannesBuchner** [comment]
Seems to be related: https://github.com/blue-yonder/pyscaffold/issues/136

**Comment by JohannesBuchner** [comment]
Solved it by running 

`$ pip2 install . --user`

and, before that, `pip2 install pyscaffold==2.5.7 --user`
