### ISSUE TITLE
Gaussian Prior minimum hardcoded Crash

### ISSUE THREAD

**Issue by cbrisboi** [giacomov/astromodels#66]
I'm trying to test a Gaussian prior for the flux. Here is the traceback. The minimum seems to be hardcoded in priors.py as 1e-12

Looking at my model: 
`source_name = "Crab"
crab_ra  = 83.63
crab_dec = 22.01

from astromodels.functions.priors import Gaussian as GP
spectrum=threeML.Powerlaw()
source1=threeML.PointSource(name, ra=crab_ra, dec=crab_dec, spectral_shape=spectrum)

spectrum.index.value  = -2.63
spectrum.index.bounds = (-4.0, -1.0)
spectrum.index.set_uninformative_prior(astromodels.Uniform_prior)
spectrum.index.fix    = False

spectrum.piv.value    = 7.0 * threeML.u.TeV
spectrum.piv.fix      = True

spectrum.K.value      = 3.5e-11 * fluxUnit
#spectrum.K.bounds     = (1e-16 * fluxUnit, 1e-10*fluxUnit)                                                                                                                          
#spectrum.K.bounds = (None, None)                                                                                                                                                    
spectrum.K.prior = GP()

spectrum.K.prior.mu.units=fluxUnit

spectrum.K.prior.sigma.units=fluxUnit
spectrum.K.prior.sigma.min=1e-29*fluxUnit

spectrum.K.prior.mu = 0*fluxUnit
spectrum.K.prior.sigma= 1.16244891e-13 * fluxUnit
spectrum.K.fix        = False                                                                                                                                                                   
model=threeML.Model(source1)`

Setting the spectrum.K.prior.sigma.min does not seem to have any effect (regardless of whether or not units multiplied against it). I provided the traceback below:

`Traceback (most recent call last):
  File "/Users/chad/software_base/aerie/src/liff/examples/3ml/untested/fitModel/fitModel.py", line 291, in <module>
    execfile(options.model)
  File "crab_bayes_gauss.model", line 38, in <module>
    model=threeML.Model(source1)
  File "/Users/chad/hawc/astromodels/astromodels/core/model.py", line 55, in __init__
    super(Model, self).__init__("__root__")
  File "/Users/chad/hawc/astromodels/astromodels/core/tree.py", line 38, in __init__
    assert is_valid_variable_name(name), "Illegal characters in name %s. You can only use letters and numbers, " \
  File "/Users/chad/hawc/astromodels/astromodels/utils/valid_variable.py", line 14, in is_valid_variable_name
    parse('{} = None'.format(string_to_check))
  File "/Users/chad/hawc/astromodels/astromodels/core/parameter.py", line 105, in handle_quantity
    return method(instance, new_value, *args, **kwargs)
  File "/Users/chad/hawc/astromodels/astromodels/core/parameter.py", line 425, in _set_value
    self.name, new_value, self.min_value))
astromodels.core.parameter.SettingOutOfBounds: Trying to set parameter sigma = 1.16244891e-22, which is less than the minimum allowed 1e-12`

**Comment by cbrisboi** [comment]
Found the issue. As we talked on slack, being 100 sigma away from mu might cause problems...

Thanks!
